name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        run: |
          docker build \
            -f Dockerfile \
            -t captaintest/mentor:${{ inputs.version }} .

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Docker Push
        run: docker push captaintest/mentor:${{ inputs.version }}
